ecommerce/ecommerce/cart/urls.py
from django.urls import path

from . import views
app_name='cart'
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

ecommerce/ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerce/', include('ecommerceapp.urls')),
    path('search/', include('searchapp.urls')),
    path('cart/', include('cart.urls')),

]
if settings.DEBUG:
     urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
     urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/ecommerce/ecommerceapp/urls.py
from django.urls import path

from ecommerceapp import views
app_name='ecommerceapp'
urlpatterns = [
    path('',views.allcategories,name='allcategories'),
    path('<slug:c_slug>/', views.allcategories, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>', views.productdetail, name='productcategorydetail'),

]

ecommerce/ecommerce/searchapp/urls.py
from django.urls import path

from . import views
app_name='searchapp'
urlpatterns = [
    path('',views.searchresults,name='searchresults'),
]

ecommerce/ecommerce/cart/models.py
from django.db import models
from ecommerceapp.models import Product


# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class Cart_items(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'Cart_items'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return '{}'.format(self.product)

ecommerce/ecommerce/ecommerceapp/models.py
from django.urls import reverse

from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('ecommerceapp:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('ecommerceapp:productcategorydetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

ecommerce/ecommerce/searchapp/models.py
from django.db import models

# Create your models here.

ecommerce/ecommerce/cart/views.py
from ecommerceapp.models import Product
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cart, Cart_items
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def _cart_id_(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id_(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id_(request))
        cart.save()
    try:
        cart_item = Cart_items.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except Cart_items.DoesNotExist:
        cart_item = Cart_items.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id_(request))
        cart_items = Cart_items.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id_(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = Cart_items.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id_(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = Cart_items.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerce/ecommerce/ecommerceapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# Create your views here.
# def index(request):
#     return HttpResponse("hello")


def allcategories(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, "category.html", {'category': c_page, 'products': products})


def productdetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

ecommerce/ecommerce/searchapp/views.py
from django.shortcuts import render
from ecommerceapp.models import Product
from django.db.models import Q


# Create your views here.

def searchresults(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request, 'search.html', {'query': query, 'products': products})

ecommerce/ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/67a6ca9f86.js" crossorigin="anonymous"></script>
    <meta name="description" content="{%  block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}{% endblock %}
</div>
{% include 'footer.html' %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</body>
</html>

ecommerce/ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Your Cart is exciting!!Proceed to review your goodies and place order.
{% endblock %}
{% block title %}
    Cart-Cart and CO pvt ltd.
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Cart is empty!
        </h1>
        <br>
        <P class="text-center">
            Wish to fill it with some goodies?<a href="{% url 'ecommerceapp:allcategories' %}"></a>
        </P>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Cart is Ready!
        </h1>
        <br>
    </div>
</div>
<div class="row mx_auto">
    <div class="col-12 col-sm-12 col-lg-6 text-center">
        <table class="table my_cart_table">
            <thead class="my_thead">
            <tr>
                <th colspan="5">
                    Your picks
                </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items%}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded cart_image" style="width:200px; height:100px;"></a>
                </td>
                <td class="text-center">
                    {{cart_item.product.name}}
                    <br>
                    SKU:{{cart_item.product.id}}
                    <br>
                    Price:${{cart_item.product.price}}
                    <br>
                    Quantity:{{cart_item.quantity}} x ${{cart_item}}
                </td>
                <td>
                    $ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_cart"><i class="fa-solid fa-square-plus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-square-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-regular fa-trash-can custom_icon"></i></a>

                </td>
                {% else %}
                <td>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-square-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-regular fa-trash-can custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-lg-6 text-center">
        <table class="table my_cart_table">
            <thead class="my_thead">
            <th>
                Checkout
            </th>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review Your cart before placing the order.
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Your Total sum is :<strong>{{total}}</strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx_auto">
            <a href="{% url 'ecommerceapp:allcategories' %}" class="btn btn-secondary my_custom_button">Want to Continue Shopping?</a>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

ecommerce/ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.description|truncatewords:155}}
    {% else %}
        Welcome to The Cart & Co. Where everything is a touch away!
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{category.name}}-The Cart & Co.
    {% else %}
       Make your cart Rn
    {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
<div class="container">
    <div xmlns="http://www.w3.org/1999/html">
                <div>
                    <div class="row my_row">
                        <div class="mx_auto">
                            <p>
                                <a href="{% url  'ecommerceapp:allcategories' %}">Our Collection</a>
                            </p>
                        </div>
                    </div>
                </div>
    </div>
        {% endif %}
    <div class="mx_auto">
            {% if category %}
            <div>
                    <center><img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" width="1250px" height="700px"></center>
            </div>
    </div>
    <br>
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text-justify">{{category.description}}</p>
    </div>
        {% else %}
            <div>
               <center><img class="my_image my_image_padding" src="{% static 'img/banner.jpg' %}" alt="Our Products" width="1300" height="700"></center>
            </div>
            <br>
            <div>
                <h1 class="text-center my_title">Our Collection</h1>
                <p class="text-justify">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type book. It has survived not five centuries, also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
            </div>
        {% endif %}<center>
<div>
    <div class="row mx-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-3 xol-lg-3">
            <div class="text-center" style="min-width:18rem;">
                <div class="col-md-12">
                <a href="{{product.get_url}}"><img class="card-img-top my_img" src="{{product.image.url}}" alt="{{product.name}}"width="1000" height="300"> </a>
                </div>
                <div class="card body">
                    <h4>{{product.name}}</h4>
                    <h3>{{product.price}}</h3>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %}active{% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div></center>
    </div>
{% endblock %}

ecommerce/ecommerce/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">
        Acopy;The Cart & Co. Pvt ltd. All rights reserved
    </p>
</div>

ecommerce/ecommerce/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'ecommerceapp:allcategories' %}"></a> <img src="{% static 'img/logo1.png' %}" alt="logimage" width="200" height="200">
  </center>
</header>

ecommerce/ecommerce/templates/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#"><i class="fa-solid fa-house"></i></a>
        </li>
        <li class="nav-item dropdown {% if 'ecommerceapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'ecommerceapp:allcategories' %}">All Products</a></li>
              {% for cat in links %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail'%}"><i class="fa-solid fa-cart-shopping"></i></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'searchapp:searchresults' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerce/ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        {{product.description|truncatewords:155}}
        Welcome to The Cart & Co. Where everything is a touch away!
{% endblock %}
{% block title %}
    {% if product %}
        {{product.name}}-The Cart & Co.
    {% endif %}
{% endblock %}
{% block content %}
<div class="row my_product-row">
    <div class="mx_auto">
        <p> <a href="{% url 'ecommerceapp:allcategories' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}</p>
    </div>
</div>
<div class="container">
    <br><center>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-lg-12">
            <div style="min-width:18rem">
                <img class="my_image_padding" src="{{product.image.url}}" alt="{{product.name}}">
            </div>
        </div>
            <div class="col-12 col-sm-12 col-lg-12">
                <div>
                    <h1 class="my_product_title">{{product.name}}</h1>
                    <p>${{product.price}}</p>
                    <p class="my_about_title">About the product</p>
                    <p class="text-justify my_desc">{{product.description}}</p>
                    {% if product.stock <= 0 %}
                    <p class="text-justify" style="color:#d85c24">OUT OF STOCK</p>
                    {% else %}
                </div>
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
            {% endif %}
        </div></center>
    </div>
{% endblock %}

ecommerce/ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Here are the best sellers from your search
{% endblock %}
{% block title %}
    Search results
{% endblock %}
{% block content %}
    <div>
        <p class="text-center my_search">Here are the best sellers from:<b> "{{query}}" </b> </p>
    </div>
    <div class="container">
        <div class="row mx-auto">
                {% for product in products %}
                    <div class="my_bottom_margin col-9 col-sm-12 col-md-3 xol-lg-3">
                        <div class="text-center" style="min-width:18rem;">
                            <div class="col-md-12">
                                <a href="{{product.get_url}}"><img class="card-img-top my_img" src="{{product.image.url}}" alt="{{product.name}}"width="1000" height="300"> </a>
                            </div>
                            <div class="card body">
                                <h4>{{product.name}}</h4>
                                <h3>{{product.price}}</h3>
                            </div>
                        </div>
                    </div>
                {% empty %}
    <div class="row mx-auto">
        <p class="text-center my_search"> No results Found</p>
    </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}